import './globals.css';
import Navbar from '@/Components/Shared/Navbar';
import NextTopLoader from 'nextjs-toploader';
import Footer from '@/Components/Shared/Footer';
import { Inter, Poppins, Lobster } from "next/font/google";
// import { Hidayatullah } from "next/font/local";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: "--font-poppins"
});

const lobstar = Lobster({
  subsets: ['latin'],
  weight: ['400'],
  variable: "--font-lobstar"
});

// const hidayatullah = Hidayatullah({
//   src: '/fonts/hidayatullah_DEMO.ttf',
//   variable: '--font-hidayat'
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        />
      </head>
      <NextTopLoader color="red" speed={200} />
      <body className={`${poppins.variable} ${lobstar.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
